# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

##########################################################
#    Declare these values as environment variables!!!    #
#    - PFX: Location of PFX file for code sign           #
#    - PFX_PW: Password of PFX file                      #
##########################################################
vars:
  DIST: ../.dist
  CONFIGURATION: Release
  PLATFORM: Any CPU
  MSBUILD: 'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe'
  SIGNTOOL: 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe'

dotenv:
  - .env.local
  - .env.{{.ENV}}
  - .env

tasks:
  default:
    cmds:
      - task: build
      - task: cleanup
      - task: sign
  build:
    cmds:
      - task: build:clear-temp
      - task: build:hammer-launcher
      - task: build:pathed
      - task: build:rcalc
      - task: build:skip-uac
  build:clear-temp:
    dir: clear-temp
    cmds:
      - '"{{.MSBUILD}}" ClearTemp.slnx -t:build -restore -p:RestorePackagesConfig=true -p:Configuration={{.CONFIGURATION}} -p:Platform="{{.PLATFORM}}"'
      - mkdir {{.DIST}} 2> /dev/null
      - mv bin/{{.CONFIGURATION}}/ClearTemp.exe {{.DIST}}
      - mv bin/{{.CONFIGURATION}}/ClearTemp.txt {{.DIST}}
  build:hammer-launcher:
    dir: hammer-launcher
    cmds:
      - '"{{.MSBUILD}}" HammerLauncher.slnx -t:build -restore -p:RestorePackagesConfig=true -p:Configuration={{.CONFIGURATION}} -p:Platform="{{.PLATFORM}}"'
      - mkdir {{.DIST}} 2> /dev/null
      - mv bin/{{.CONFIGURATION}}/HammerLauncher.exe {{.DIST}}
  build:pathed:
    dir: pathed
    cmds:
      - '"{{.MSBUILD}}" Pathed.slnx -t:build -restore -p:RestorePackagesConfig=true -p:Configuration={{.CONFIGURATION}} -p:Platform="{{.PLATFORM}}"'
      - mkdir {{.DIST}} 2> /dev/null
      - mv bin/{{.CONFIGURATION}}/Pathed.exe {{.DIST}}
  build:rcalc:
    dir: rcalc
    cmds:
      - '"{{.MSBUILD}}" rcalc.slnx -t:build -restore -p:RestorePackagesConfig=true -p:Configuration={{.CONFIGURATION}} -p:Platform="{{.PLATFORM}}"'
      - mkdir {{.DIST}} 2> /dev/null
      - mv bin/{{.CONFIGURATION}}/rcalc.exe {{.DIST}}
  build:skip-uac:
    dir: skip-uac
    cmds:
      - '"{{.MSBUILD}}" SkipUAC.slnx -t:build -restore -p:RestorePackagesConfig=true -p:Configuration={{.CONFIGURATION}} -p:Platform="{{.PLATFORM}}"'
      - mkdir {{.DIST}} 2> /dev/null
      - mv bin/{{.CONFIGURATION}}/SkipUAC.exe {{.DIST}}
  cleanup:
    cmds:
      - taskkill /f /im MSBuild.exe
  sign:
    cmds:
      - task: sign:clear-temp
      - task: sign:hammer-launcher
      - task: sign:pathed
      - task: sign:rcalc
      - task: sign:skip-uac
  sign:clear-temp:
    cmds:
      - '"{{.SIGNTOOL}}" sign /f "{{.PFX}}" /p "{{.PFX_PW}}" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/ClearTemp.exe'
  sign:hammer-launcher:
    cmds:
      - '"{{.SIGNTOOL}}" sign /f "{{.PFX}}" /p "{{.PFX_PW}}" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/HammerLauncher.exe'
  sign:pathed:
    cmds:
      - '"{{.SIGNTOOL}}" sign /f "{{.PFX}}" /p "{{.PFX_PW}}" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/Pathed.exe'
  sign:rcalc:
    cmds:
      - '"{{.SIGNTOOL}}" sign /f "{{.PFX}}" /p "{{.PFX_PW}}" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/rcalc.exe'
  sign:skip-uac:
    cmds:
      - '"{{.SIGNTOOL}}" sign /f "{{.PFX}}" /p "{{.PFX_PW}}" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/SkipUAC.exe'
