# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

##########################################################
#    Declare these values as environment variables!!!    #
#    - PFX: Location of PFX file for code sign           #
#    - PFX_PW: Password of PFX file                      #
##########################################################
env:
  CS_CONFIGURATION: Release
  CS_DIST: ../.dist
  CS_DOTNET: 'C:\Program Files\dotnet\dotnet.exe'
  CS_FRAMEWORK: net10.0
  CS_SIGNTOOL: 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe'
  CS_TARGET: win-x64

dotenv:
  - .env.local
  - .env.{{.ENV}}
  - .env

tasks:
  default:
    cmds:
      - task: build
      - task: cleanup
      - task: sign
  build:
    cmds:
      - task: build:clear-temp
      - task: build:hammer-launcher
      - task: build:pathed
      - task: build:rcalc
  build:clear-temp:
    dir: clear-temp
    cmds:
      - '"$CS_DOTNET" publish -c $CS_CONFIGURATION -r $CS_TARGET'
      - 'mkdir "$CS_DIST" 2> /dev/null'
      - 'mv bin/$CS_CONFIGURATION/$CS_FRAMEWORK/$CS_TARGET/publish/ClearTemp.exe "$CS_DIST"'
      - 'mv bin/$CS_CONFIGURATION/$CS_FRAMEWORK/$CS_TARGET/publish/ClearTemp.txt "$CS_DIST"'
  build:hammer-launcher:
    dir: hammer-launcher
    env:
      CS_FRAMEWORK: net10.0-windows
    cmds:
      - '"$CS_DOTNET" publish -c $CS_CONFIGURATION -r $CS_TARGET'
      - 'mkdir "$CS_DIST" 2> /dev/null'
      - 'mv bin/$CS_CONFIGURATION/$CS_FRAMEWORK/$CS_TARGET/publish/HammerLauncher.exe "$CS_DIST"'
  build:pathed:
    dir: pathed
    env:
      CS_FRAMEWORK: net10.0-windows
    cmds:
      - '"$CS_DOTNET" publish -c $CS_CONFIGURATION -r $CS_TARGET'
      - 'mkdir "$CS_DIST" 2> /dev/null'
      - 'mv bin/$CS_CONFIGURATION/$CS_FRAMEWORK/$CS_TARGET/publish/Pathed.exe "$CS_DIST"'
  build:rcalc:
    dir: rcalc
    env:
      CS_FRAMEWORK: net10.0-windows
    cmds:
      - '"$CS_DOTNET" publish -c $CS_CONFIGURATION -r $CS_TARGET'
      - 'mkdir "$CS_DIST" 2> /dev/null'
      - 'mv bin/$CS_CONFIGURATION/$CS_FRAMEWORK/$CS_TARGET/publish/rcalc.exe "$CS_DIST"'
  cleanup:
    ignore_error: true
    cmds:
      - taskkill /f /im MSBuild.exe
      - taskkill /f /im VBCSCompiler.exe
      - taskkill /f /im dotnet.exe
  sign:
    cmds:
      - task: sign:clear-temp
      - task: sign:hammer-launcher
      - task: sign:pathed
      - task: sign:rcalc
  sign:clear-temp:
    cmds:
      - '"$CS_SIGNTOOL" sign /f "$PFX" /p "$PFX_PW" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/ClearTemp.exe'
  sign:hammer-launcher:
    cmds:
      - '"$CS_SIGNTOOL" sign /f "$PFX" /p "$PFX_PW" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/HammerLauncher.exe'
  sign:pathed:
    cmds:
      - '"$CS_SIGNTOOL" sign /f "$PFX" /p "$PFX_PW" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/Pathed.exe'
  sign:rcalc:
    cmds:
      - '"$CS_SIGNTOOL" sign /f "$PFX" /p "$PFX_PW" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com .dist/rcalc.exe'
