//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Resources.Locale {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LConsole {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LConsole() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Resources.Locale.LConsole", typeof(LConsole).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to parse argument: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorFailedToParse {
            get {
                return ResourceManager.GetString("ErrorFailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpDefaultValue {
            get {
                return ResourceManager.GetString("HelpDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiding UID, cropping area, etc., are determined by game title.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpGameDescription {
            get {
                return ResourceManager.GetString("HelpGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tower of Fantasy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpGameTOF_1 {
            get {
                return ResourceManager.GetString("HelpGameTOF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : tower-of-fantasy, tf, tof과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpGameTOF_2 {
            get {
                return ResourceManager.GetString("HelpGameTOF_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wuthering Waves과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpGameWuWa_1 {
            get {
                return ResourceManager.GetString("HelpGameWuWa_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : wuthering-waves, wuwa, ww과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpGameWuWa_2 {
            get {
                return ResourceManager.GetString("HelpGameWuWa_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Background&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpBackground_1 {
            get {
                return ResourceManager.GetString("HelpOpBackground_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can move freely while the dialog is displayed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpBackground_2 {
            get {
                return ResourceManager.GetString("HelpOpBackground_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : background, b, bg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpBackground_3 {
            get {
                return ResourceManager.GetString("HelpOpBackground_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Center&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpCenter_1 {
            get {
                return ResourceManager.GetString("HelpOpCenter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog is displayed in center of screen, with black background.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpCenter_2 {
            get {
                return ResourceManager.GetString("HelpOpCenter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : center, c과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpCenter_3 {
            get {
                return ResourceManager.GetString("HelpOpCenter_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depending on the situation of the screenshot, the crop area will be determined. UID area will be hidden automatically.\nAfter the crop, the screenshot will be converted to WebP format.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOperationDescription {
            get {
                return ResourceManager.GetString("HelpOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Foreground 0&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground0_1 {
            get {
                return ResourceManager.GetString("HelpOpForeground0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog is displayed with 0 option while locking your movement.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground0_2 {
            get {
                return ResourceManager.GetString("HelpOpForeground0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : foreground0, f0, fg0, foreground-0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground0_3 {
            get {
                return ResourceManager.GetString("HelpOpForeground0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Foreground 1&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground1_1 {
            get {
                return ResourceManager.GetString("HelpOpForeground1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog is displayed with 1 option while locking your movement.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground1_2 {
            get {
                return ResourceManager.GetString("HelpOpForeground1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : foreground1, f1, fg1, foreground-1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground1_3 {
            get {
                return ResourceManager.GetString("HelpOpForeground1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Foreground 2&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground2_1 {
            get {
                return ResourceManager.GetString("HelpOpForeground2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog is displayed with 2 options while locking your movement.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground2_2 {
            get {
                return ResourceManager.GetString("HelpOpForeground2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : foreground2, f2, fg2, foreground-2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground2_3 {
            get {
                return ResourceManager.GetString("HelpOpForeground2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Foreground 3&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground3_1 {
            get {
                return ResourceManager.GetString("HelpOpForeground3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog is displayed with 3 options while locking your movement.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground3_2 {
            get {
                return ResourceManager.GetString("HelpOpForeground3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : foreground3, f3, fg3, foreground-3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground3_3 {
            get {
                return ResourceManager.GetString("HelpOpForeground3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screenshot is &apos;Foreground 4&apos; dialog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground4_1 {
            get {
                return ResourceManager.GetString("HelpOpForeground4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog is displayed with 4 options while locking your movement.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground4_2 {
            get {
                return ResourceManager.GetString("HelpOpForeground4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : foreground4, f4, fg4, foreground-4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpForeground4_3 {
            get {
                return ResourceManager.GetString("HelpOpForeground4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not crop the screenshot.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpFull_1 {
            get {
                return ResourceManager.GetString("HelpOpFull_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : full, f과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpOpFull_2 {
            get {
                return ResourceManager.GetString("HelpOpFull_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide UID, crop, resize game screenshots, and convert them to WebP format.\nThe size of the screenshots must be 1920x1080. If not, they will be considered as &apos;already processed game screenshots&apos;, so only resizing will be applied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpProgramDescription {
            get {
                return ResourceManager.GetString("HelpProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Force message language to English.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpSwtEnglish_1 {
            get {
                return ResourceManager.GetString("HelpSwtEnglish_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show help message.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpSwtHelp_1 {
            get {
                return ResourceManager.GetString("HelpSwtHelp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show verbose messages. Mainly for debugging.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpSwtVerbose_1 {
            get {
                return ResourceManager.GetString("HelpSwtVerbose_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show version information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpSwtVersion_1 {
            get {
                return ResourceManager.GetString("HelpSwtVersion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must specify where the screenshot files are located.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpTargetDescription {
            get {
                return ResourceManager.GetString("HelpTargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory where the screenshot file(s) is located.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpTgtTarget_1 {
            get {
                return ResourceManager.GetString("HelpTgtTarget_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It must be existing directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpTgtTarget_2 {
            get {
                return ResourceManager.GetString("HelpTgtTarget_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current working directory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpTgtTarget_3 {
            get {
                return ResourceManager.GetString("HelpTgtTarget_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valid values과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpValidValues {
            get {
                return ResourceManager.GetString("HelpValidValues", resourceCulture);
            }
        }
    }
}
